title: EL BLOGG DE MACARENA
description:  VIDEOJUEGOS Y RETOS
permalink: ':title/'
baseurl: "/" 
url: "https://maca-gamer.github.io/" 
site-twitter: 


author: EL BLOGG DE MACARENA
author-img: ugamer.jpg  
about-author: Este blogg va de videojuegos y retos con invitados sorpresas y sobretodo haré retos con mi hermana mayor.
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
